project:
  type: website
  output-dir: docs
  resources:
    - CNAME
website:
  title: "magasinet"
  site-url: https://terningkast.net
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Om oss
        href: about.qmd

format:
  html:
    theme: pandoc
    css: styles.css
    toc: true


